# Standard Transformer Baseline (300k Params, Compute Matched)
name: baselines.transformer@StandardTransformer
loss:
  name: losses@ACTLossHead
  loss_type: softmax_cross_entropy

_target_: models.baselines.transformer.StandardTransformer

# Parameters (Matched to ~299k total)
num_layers: 8
hidden_size: 40
num_heads: 4
expansion: 2.666 # Inter = 256
pos_encodings: "rope"
rms_norm_eps: 1e-5
rope_theta: 10000.0
forward_dtype: "bfloat16"

# Dataset specific defaults
carry_loss_weight: 1.0
